### PR TITLE
Feature selection

### PR DESCRIPTION
**Pull request by scanhex12**
## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [x] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Closing issues

#712

### CODE REVIEW

**Comment by alex-hse-repository** [comment]
<p>But we can leave this version as well</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/875/discussion/#comment-1621741410'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alex-hse-repository** [comment]
<p>May you check the results with <code>fast_redundancy=False</code></p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/875/discussion/#comment-1621741556'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alex-hse-repository** [comment]
<p>If <code>ModelRelevanceTable</code> works worse than <code>StatisticsRelevanceTable</code> we can actually leave statistics, here we want to show that feature selection improves quality or improves speed without significance decrease in quality    </p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/875/discussion/#comment-1621741556'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Mr-Geekman** [comment]
<p>For MRMR both ModelRelevanceTable and StatisticsRelevanceTable works worse than a baseline. I'll write all the results in the next message to compare.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/875/discussion/#comment-1621741556'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Mr-Geekman** [comment]
<p>These are results on my personal laptop.</p><pre class="ql-syntax" spellcheck="false">SMAPE baseline: 8.094
Time baseline: 79.353
</pre><p> </p><p><code>ModelRelevanceTable</code> + <code>fast_redundancy=True</code></p><p>- SMAPE: 7.416</p><p>- Time: 43.722</p><p> </p><p><code>StatisticsRelevanceTable</code> + <code>fast_redundancy=True</code></p><p>- SMAPE: 13.262</p><p>- Time: 42.955</p><p> </p><p><code>ModelRelevanceTable</code> + <code>fast_redundancy=False</code></p><p>- SMAPE: 7.197</p><p>- Time: 143.238</p><p> </p><p><code>StatisticsRelevanceTable</code> + <code>fast_redundancy=False</code></p><p>- SMAPE: 13.262</p><p>- Time: 144.947</p><p> </p><p>It seems like bug fix also changed the results for MRMR.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/875/discussion/#comment-1621741556'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alex-hse-repository** [comment]
<p>I guess we can take <code>ModelRelevanceTable</code>&nbsp;+&nbsp;<code>fast_redundancy=True</code></p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/875/discussion/#comment-1621741556'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by alex-hse-repository — APPROVED** [review]

**Pull request merged**
