### PR TITLE
Create notebook `forecast_interpretation.ipynb`

### LINKED ISSUE #1189: Update notebooks with the results of the track
### 🚀 Feature Request

Add info about the forecast decomposition in the notebooks 

### Proposal

1. In `custom_transform_and_model.ipynb`
- Fix code for custom models to run without fails
- Add example of implementing the forecast decomposition logic for LightGBM -- it can be done similar to [Catboost](https://github.com/tinkoff-ai/etna/blob/5cc7c87dea26346a2d4378df67d8036ce878d821/etna/models/catboost.py#L129). See `pred_contrib` parameter in [predict](https://lightgbm.readthedocs.io/en/v3.3.2/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor.predict)
2. Create notebook `forecast_interpretation.ipynb`:
- Show how to get forecast decomposition for CatBoost, SARIMA, BATS models and visualize the decomposition
- Show how to get the forecast components into TSDataset
- Show the how to get and plot feature relevance with `plot_feature_relevance` for both types of relevance table

### Test cases

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by brsnw250**
## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

Resolves second point from #1189

## Closing issues

closes #1189

### CODE REVIEW

**Comment by brsnw250** [comment]
<p>We have a 21-day lag, so we cannot exceed this number.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506397851'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by brsnw250** [comment]
<p>Examples with separate calls of <code>forecast</code> and <code>predict</code> will be added in a separate section.  </p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506397934'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alex-hse-repository** [comment]
<p>We can use 21 lag with horizon 21</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506397851'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alex-hse-repository** [comment]
<p>We can't leave this line this way because it is not correct way to use it, <code>plot_forecast_components</code> should get the components via dataset interface, not via names </p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506397934'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alex-hse-repository** [comment]
<p>Better to create dataset out of target components</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506397961'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alex-hse-repository** [comment]
<p>Concluding sentence about the whole notebook</p><p> </p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506398014'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by brsnw250** [comment]
<p>The first sentence is redundant, will remove it.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1508172325'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by brsnw250** [comment]
<p>Added</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1508172306'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by brsnw250** [comment]
<p>Added</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506398014'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by alex-hse-repository** [comment]
<p>But effects of what?)))</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506397865'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by brsnw250** [comment]
<p>"decomposition down to components" just doesn't sound good.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1220/discussion/#comment-1506397865'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by alex-hse-repository — APPROVED** [review]

**Pull request merged**
